# Generated by Django 2.0.7 on 2021-01-19 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=10)),
                ('under_construction', models.BooleanField()),
                ('rera', models.BooleanField()),
                ('rooms', models.PositiveSmallIntegerField()),
                ('room_type', models.CharField(max_length=4)),
                ('area', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ready_to_move', models.BooleanField()),
                ('resale', models.BooleanField()),
                ('location', models.CharField(max_length=100)),
                ('loc_long', models.DecimalField(decimal_places=10, max_digits=14)),
                ('loc_lat', models.DecimalField(decimal_places=10, max_digits=14)),
                ('price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
